import androidx.compose.runtime.Composable
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavType
import androidx.navigation.compose.NavHost
import androidx.navigation.compose.composable
import androidx.navigation.compose.rememberNavController
import androidx.navigation.navArgument
import com.cs407.settlersofmadison.ui.game.GameScreen
import com.cs407.settlersofmadison.ui.lobby.HostLobbyScreen
import com.cs407.settlersofmadison.ui.lobby.HostSetupScreen
import com.cs407.settlersofmadison.ui.lobby.JoinLobbyScreen
import com.cs407.settlersofmadison.ui.lobby.JoinSetupScreen
import com.cs407.settlersofmadison.ui.lobby.LobbyViewModel
import com.cs407.settlersofmadison.ui.main.MainMenuScreen

@Composable
fun AppNav() {
    val navController = rememberNavController()
    val vm: LobbyViewModel = viewModel()   // ONE shared VM per device

    NavHost(
        navController = navController,
        startDestination = "main"
    ) {
        composable("main") {
            MainMenuScreen(
                onCreateRoom = { navController.navigate("hostSetup") },
                onJoinRoom   = { navController.navigate("joinSetup") }
            )
        }

        composable("hostSetup") {
            HostSetupScreen(
                vm = vm,
                onHosted = { navController.navigate("hostLobby") },
                onBack = { navController.popBackStack() }
            )
        }

        composable("hostLobby") {
            HostLobbyScreen(
                vm = vm,
                onBackToMain = {
                    vm.leave()
                    navController.popBackStack("main", inclusive = false)
                },
                onStartGame = {
                    // CHANGED: Get the seed (generated by host) and pass it
                    val seed = vm.gameSeed.value
                    navController.navigate("game/host/$seed")
                }
            )
        }

        composable("joinSetup") {
            JoinSetupScreen(
                vm = vm,
                onJoined = { navController.navigate("joinLobby") },
                onBack = { navController.popBackStack() }
            )
        }

        composable("joinLobby") {
            JoinLobbyScreen(
                vm = vm,
                onBackToMain = {
                    vm.close()
                    navController.popBackStack("main", inclusive = false)
                },
                onGameStarted = {
                    // CHANGED: Get the seed (received from host) and pass it
                    val seed = vm.gameSeed.value
                    navController.navigate("game/guest/$seed")
                }
            )
        }

        // CHANGED: Route accepts seed argument
        composable(
            route = "game/{role}/{seed}",
            arguments = listOf(
                navArgument("role") { type = NavType.StringType },
                navArgument("seed") { type = NavType.LongType }
            )
        ) { backStackEntry ->
            val role = backStackEntry.arguments?.getString("role") ?: "host"
            val seed = backStackEntry.arguments?.getLong("seed") ?: 0L

            GameScreen(
                localPlayerId = role,
                seed = seed,
                onExit = {
                    vm.leave()
                    navController.popBackStack("main", inclusive = false)
                }
            )
        }
    }
}